### PR TITLE
Editor mode

### PR DESCRIPTION
**Pull request by matibarriento**
Update highlightjs, codemirror and modes. 
Add support for groovy, nginx, yaml, less and typescript.
Fix some modes and improve detection.

These are files that i change, all the others are libs update.
- static/js/main.js
- templates/_new.html
- templates/helpers.html

Improved detection.
Highlightjs detect the languages (if it could) and with a dict, change the editor mode. Same logic when user change the language dropdown. Codemirror recibe in a specific way the language ("text/x-python")
Now detection and set editor mode code are more clean and add other languages will be more easy.

Hope you like!

### CODE REVIEW

**Comment by facundobatista** [comment]
Trying to remember... we agreed on Telegram to split this branch in manageable ones, right?

**Comment by matibarriento** [comment]
As I understood, I should list the modified files except libs update. Updates and changes come together

**Comment by matibarriento** [comment]
Merged with current version

**Comment by facundobatista** [comment]
Awesome, thank you very much!

And sorry for the delay in reviewing this!

**Pull request merged**
