### PR TITLE
Python Sprint in Rosario

### PR DESCRIPTION
**Pull request by matibarriento**
Fixed issues #21 #50 #62 

On issue #62 there isn't a notification, the three div reload itself when a new version is submited.

I hope our work make kilink/linkode better.

### CODE REVIEW

**Comment by matibarriento** [comment]
Fixed issues #21 #50 #62

On issue #62 there isn't a notification, the three div reload itself when a new version is submited.

I hope our work make kilink/linkode better.

**Comment by facundobatista** [comment]
Ok, starting now to seriously take a look at this.

*Really* you should consider proposing different PRs, one for each problem solved. Considering all mixed up makes this too complex. I'll try to comment on different branches/issues, though.

But please, propose a PR for each issue to fix.


**Regarding issue #21**

- do not impose a maximum on lines; we don't care about that, really... the maximum should be about total length.

- one serious drawback about setting a max for lines is that you're doing:  ```lines = content.split("\n")``` and that just consumes memory and don't provides real value.

- you're calling ```self.check_content_len(content)``` twice in create_kilink.

- the beforeChange callback in the editor, is called on every user keystroke? isn't that too much? considering that this limit is a kind-of-security one, to prevent users abusing the system, can't we just put the limit server side?


**Regarding issue #50**

I like it. Can we separate this code so I merge it? Thanks!


**Regarding issue #62**

It seems to work, but it's polling, every 30 seconds or so!! We should be using push, not poll, and in the issue we talked about 

    http://stackoverflow.com/questions/12232304/how-to-implement-server-push-in-flask-framework

What happened with that??

Thanks for all your effort and time!!

**Comment by facundobatista** [comment]
BTW, sorry for all the delay in handling this... it has been some complicated weeks.

**Comment by matibarriento** [comment]
__Issie #62__
About the link, we try to implement that, but it requiere Gevent or something like that. We can't make it work, so we choose that way to have the code in the backend ready, and when any solution appear, change the stuff on the client to recive the updates on the tree.

It's not a elegant solution, and misses the notification (only update the div) but it's a start.
Also, we don't find a solution using uwsgi.

**Comment by matibarriento** [comment]
I close this pull request because the useful things are in separate pull requests.

**Pull request closed without merging**
